Repository AY2324S1-CS2103T-W09-4/tp, pull requests merged in 2023-10, with the labels that each got.

#70 Branch enhance remark
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/logic/parser/RemarkSyntaxHandler.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
Labels: enhancement

#75 feat(status): Implement saving for status feature
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Status.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/model/person/StatusTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: enhancement

#74 add score characteristic
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemarkSyntaxHandler.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Score.java
  src/main/java/seedu/address/model/person/Status.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: enhancement

#78 Update DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/Ui.png
  docs/images/viewState.png
  src/main/java/seedu/address/logic/commands/ViewCommand.java
Labels: DG, UG

#94 Release trial jar file
  src/main/java/seedu/address/MainApp.java
Labels: release
