Repository AY2324S1-CS2103T-W09-4/tp, pull requests merged in 2023-11, with the labels that each got.

#109 Branch enhance score
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/ScoreList.java
  src/main/java/seedu/address/model/statistics/SummaryStatistic.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedScoreList.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: documentation, enhancement

#110 - Updated the help window to show JABPro's UserGuide
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: bug

#111 Branch filter stats
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/create.png
  docs/images/editscore.png
  docs/images/enhancedremark.png
  docs/images/filter.png
  docs/images/remark.png
  docs/images/view.png
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/ScoreList.java
  src/main/java/seedu/address/model/statistics/StatisticMetric.java
  src/main/java/seedu/address/model/statistics/SummaryStatistic.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
Labels: enhancement, UG

#112 Branch list tags
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EventCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListTCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TagCard.java
  src/main/java/seedu/address/ui/TagListPanel.java
  src/main/java/seedu/address/ui/TagListWindow.java
  src/main/resources/view/TagListCard.fxml
  src/main/resources/view/TagListPanel.fxml
  src/main/resources/view/TagListWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: enhancement

#159 Updated the User Guide to enhance clarity for users
  docs/UserGuide.md
Labels: UG

#165 - Updated the UserGuide to highlight the difference between Beginner …
  docs/UserGuide.md
  docs/team/scarletblanks.md
Labels: UG, PPP

#167 Updated PPP to reflect UG
  docs/team/sk2001git.md
Labels: PPP

#162 Fix PE-D bugs related to tags
  src/main/java/seedu/address/logic/commands/CreateTagCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonInformationPanel.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: bug

#171 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/EventSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/event.png
  docs/images/eventwindow.png
  docs/stylesheets/main.css
Labels: DG

#180 Update UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/addL.png
  docs/images/addLfail.png
  docs/images/blue.png
  docs/images/brown.png
  docs/images/event.png
  docs/images/eventfail.png
  docs/images/eventstab.png
  docs/images/eventwin.png
  docs/images/eventwindow.png
  docs/images/github.png
  docs/images/green.png
  docs/images/linkedin.png
  docs/images/linkedinfail.png
  docs/images/orange.png
  docs/images/purple.png
  docs/images/red_1.png
  docs/images/schedule.png
  docs/images/uibreak.png
  docs/images/yellow.png
  docs/stylesheets/main.css
Labels: UG

#191 Added an activity diagram for set
  docs/AboutUs.md
  docs/diagrams/SetActivityDiagram.puml
Labels: documentation

#197 Branch user guide
  docs/UserGuide.md
Labels: UG

#214 Updated the developer guide to repair confusing statements
  docs/DeveloperGuide.md
Labels: DG

#216 Bugfix: fix bug in editing scores
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: bug
